= README for tnw (The New War)

tnw is a hotseat multiplayer version of vms-empire, a simulation of full-scale
war between emperors. The object of the game is to conquer all enemies and
become the sole ruler.

This is a multiplayer 4X strategy game where each player takes turns controlling
their forces on the same screen. Battle for territory, build armies and fleets,
capture cities, and eliminate your opponents.

== Multiplayer

Run with 2-4 players:
    ./tnw -p 2    # 2 players
    ./tnw -p 3    # 3 players
    ./tnw -p 4    # 4 players

Player Colors:
    Player 1: Red Armies
    Player 2: Yellow Armies
    Player 3: Purple Armies
    Player 4: White Armies

Controls are the same as classic empire - take turns entering commands.
Press 'E' to end your turn and pass control to the next player.

== Building

    make clean && make

Requires: ncurses

== Original Empire

This code originated under VMS by Chuck Simmons <chuck@amdahl.com>. Since
around 1990 it was maintained by Eric S. Raymond <esr@thyrsus.com>.

vms-empire is the ancestor of all multiplayer 4X simulations, including
Civilization and Master of Orion.
